### ISSUE TITLE
 cannot import name 'PILLOW_VERSION'

### ISSUE THREAD

**Issue by azuryl** [NVIDIA/retinanet-examples#106]
retinanet infer retinanet_rn50fpn.pth --images /coco/images/val2017/ --annotations /coco/annotations/instances_val2017.json
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 6, in <module>
    from retinanet.main import main
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/opt/conda/lib/python3.6/site-packages/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/opt/conda/lib/python3.6/site-packages/retinanet/model.py", line 7, in <module>
    from . import backbones as backbones_mod
  File "/opt/conda/lib/python3.6/site-packages/retinanet/backbones/__init__.py", line 3, in <module>
    from .resnet import *
  File "/opt/conda/lib/python3.6/site-packages/retinanet/backbones/resnet.py", line 1, in <module>
    import torchvision
  File "/opt/conda/lib/python3.6/site-packages/torchvision/__init__.py", line 2, in <module>
    from torchvision import datasets
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/__init__.py", line 9, in <module>
    from .fakedata import FakeData
  File "/opt/conda/lib/python3.6/site-packages/torchvision/datasets/fakedata.py", line 3, in <module>
    from .. import transforms
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/__init__.py", line 1, in <module>
    from .transforms import *
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/transforms.py", line 17, in <module>
    from . import functional as F
  File "/opt/conda/lib/python3.6/site-packages/torchvision/transforms/functional.py", line 5, in <module>
    from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION
ImportError: cannot import name 'PILLOW_VERSION'

**Comment by yashnv** [comment]
Same as #105. Closing.
