### ISSUE TITLE
error about  “ retinanet export”，this ***.pth comes from mmdetection,this cannot support?

### ISSUE THREAD

**Issue by CZYWRIT** [NVIDIA/retinanet-examples#143]
When I run "retinanet export ***   ****", this error occurs:
Loading model from epoch_12.pth...
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 11, in <module>
    load_entry_point('retinanet', 'console_scripts', 'retinanet')()
  File "/workspace/retinanet/retinanet/main.py", line 176, in main
    model, state = load_model(args, verbose=True)
  File "/workspace/retinanet/retinanet/main.py", line 91, in load_model
    model, state = Model.load(args.model)
  File "/workspace/retinanet/retinanet/model.py", line 193, in load
    model = cls(backbones=checkpoint['backbone'], classes=checkpoint['classes'])
KeyError: 'backbone'

**Comment by yashnv** [comment]
How did you produce `epoch_12.pth`? Was it from `retinanet train`?
We already have some trained models here: https://github.com/NVIDIA/retinanet-examples/releases/tag/19.04
