### ISSUE TITLE
some questions about project

### ISSUE THREAD

**Issue by CZYWRIT** [NVIDIA/retinanet-examples#146]
retina C++：
after cmake，make，run：
./infer engine.plan image.jpg
error such like this：
Loading engine...
infer: engine.cpp:868: bool nvinfer1::rt::Engine::deserialize(const void*, std::size_t, nvinfer1::IGpuAllocator&, nvinfer1::IPluginFactory*): Assertion `size >= bsize && "Mismatch between allocated memory size and expected size of serialized engine."' failed.

when train with retina：
the error was happened:

Training model for 50000 iterations...
[   18/50000] focal loss: 1.124, box loss: 0.475, 3.376s/4-batch (fw: 1.095s, bw: 2.125s), 1.2 im/s, lr: 5.8e-05
-- Process 0 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/retinanet/retinanet/main.py", line 127, in worker
    metrics_url=args.post_metrics, logdir=args.logdir, verbose=(rank == 0))
  File "/workspace/retinanet/retinanet/train.py", line 105, in train
    'Try lowering the learning rate.'))
RuntimeError: Loss is diverging!
Try lowering the learning rate.

please give me some advice ,thak you

**Comment by yashnv** [comment]
The default learning rate/scheduler were tuned for 8 GPUs. You will need to tweak around as per your number of GPUs.

**Comment by james-nvidia** [comment]
What hardware are you running this on?

**Comment by yashnv** [comment]
Closing due to inactivity. If you have questions feel free to ask here.
