### ISSUE TITLE
amp error

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#152]
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/workspace/retinanet/retinanet/main.py", line 237, in main
    worker(0, args, 1, model, state)
  File "/workspace/retinanet/retinanet/main.py", line 176, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox)
  File "/workspace/retinanet/retinanet/train.py", line 37, in train
    verbosity=is_master)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 171, in _initialize
    check_params_fp32(models)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 93, in check_params_fp32
    name, param.type()))
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 32, in warn_or_err
    raise RuntimeError(msg)
RuntimeError: Found param backbones.ResNet50FPN.features.conv1.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.

**Comment by yashnv** [comment]
What was your command?

**Comment by alicera** [comment]
odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN \
    --images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json \
    --val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json

**Comment by james-nvidia** [comment]
What command did you use to run the container? What GPU does your machine have? What driver version do you have?

**Comment by alicera** [comment]
driver is 418 , it is the problem? why

**Comment by yashnv** [comment]
what container version are you using?

**Comment by alicera** [comment]
container version  = docker version? 
I run your image ,and  I can see the GPU in the container

**Comment by yashnv** [comment]
@alicera can you post the output of these 3 commands:
```
conda list | grep -E -- 'torch|dali|apex|onnx|pycocotools'
```
and
```
nvidia-smi
```
and
```
python -c "import torch; print(torch.cuda.is_available())" 
```

**Comment by alicera** [comment]
I solve it with new nvidia driver, thanks
but the code have another problem

odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN
--images /coco/images/train2017/ --annotations /coco/annotations/instances_train2017.json
--val-images /coco/images/val2017/ --val-annotations /coco/annotations/instances_val2017.json --with-dali

-- Process 3 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 19, in _wrap
    fn(i, *args)
  File "/workspace/retinanet/retinanet/main.py", line 176, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox)
  File "/workspace/retinanet/retinanet/train.py", line 66, in train
    augment_contrast=augment_contrast, augment_hue=augment_hue, augment_saturation=augment_saturation)
  File "/workspace/retinanet/retinanet/dali.py", line 138, in __init__
    self.pipe.build()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 314, in build
    self._prepare_graph()
  File "/opt/conda/lib/python3.6/site-packages/nvidia/dali/pipeline.py", line 249, in _prepare_graph
    outputs = self.define_graph()
  File "/workspace/retinanet/retinanet/dali.py", line 78, in define_graph
    brightness_factor = random.normalvariate(1, self.augment_brightness)
NameError: name 'random' is not defined

**Comment by FeiZhuNiU** [comment]
@yashnv How to know which container version support driver version 418?

**Comment by james-nvidia** [comment]
@alicera , can you train without `--with-dali` for now? I need to make some improvements to the DALI data loader. Please let me know if that works.

**Comment by james-nvidia** [comment]
@FeiZhuNiU Are you unable to upgrade your driver?
If so, you could edit `Dockerfile` and use an earlier version of PyTorch, but you will also need to use a different branch of this repo.
For example: Use PyTorch 19.10 and repo branch `19.10`. Note that this branch does not support rotated detections.
Please open a new issue if this doesn't meet your needs.

**Comment by alicera** [comment]
thanks

**Comment by james-nvidia** [comment]
> @alicera , can you train without `--with-dali` for now? I need to make some improvements to the DALI data loader. Please let me know if that works.

@alicera this has now been resolved. Please train using `--with-dali` and let me know if it works.

**Comment by alicera** [comment]
can rotate function use ?
