### ISSUE TITLE
libcudart.so.10.1: cannot open shared object file

### ISSUE THREAD

**Issue by alicera** [NVIDIA/retinanet-examples#153]
command
```
git clone https://github.com/nvidia/retinanet-examples
docker build -t odtk:latest retinanet-examples/
docker run --gpus all --rm --ipc=host -it odtk:latest
cd retinanet-examples
python setup.py install
odtk
```

error
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk==0.2.0', 'console_scripts', 'odtk')()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2854, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2445, in load
    return self.resolve()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2451, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/opt/conda/lib/python3.6/site-packages/odtk-0.2.0-py3.6-linux-x86_64.egg/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/opt/conda/lib/python3.6/site-packages/odtk-0.2.0-py3.6-linux-x86_64.egg/retinanet/infer.py", line 13, in <module>
    from .model import Model, ModelRotated
  File "/opt/conda/lib/python3.6/site-packages/odtk-0.2.0-py3.6-linux-x86_64.egg/retinanet/model.py", line 9, in <module>
    from ._C import Engine
ImportError: libcudart.so.10.1: cannot open shared object file: No such file or directory

**Comment by yashnv** [comment]
@alicera you need to update your CUDA Toolkit to 10.2 and driver to 440 outside the container. And then run the container again.

**Comment by alicera** [comment]
how to set the threshold in the  odtk infer ,
I infer it ,the test image have the confidence score  0.01 object

**Comment by james-nvidia** [comment]
The easiest way is to filter the JSON detections by score when you plot / otherwise use them.

Alternatively you could edit this line: 
https://github.com/NVIDIA/retinanet-examples/blob/master/retinanet/infer.py#L118

Please open a new issue if you have any problems. We hope you get good use from the repo.
