### ISSUE TITLE
Failed on training

### ISSUE THREAD

**Issue by 372046933** [NVIDIA/retinanet-examples#232]
```bash
odtk train retinanet_rn18fpn.pth --backbone ResNet18FPN --images /lenna/COCO2017/images/train2017/ --annotations /lenna/COCO2017/annotations/instances_train2017.json --val-images /lenna/COCO2017/images/val2017/ --val-annotations /lenna/COCO2017/annotations/instances_val2017.json --lr 0.001 --warmup 1000 --batch 16
```

```
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/workspace/retinanet/retinanet/main.py", line 243, in main
    worker(0, args, 1, model, state)
  File "/workspace/retinanet/retinanet/main.py", line 180, in worker
    regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
  File "/workspace/retinanet/retinanet/train.py", line 40, in train
    verbosity=is_master)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 358, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 171, in _initialize
    check_params_fp32(models)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 93, in check_params_fp32
    name, param.type()))
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_amp_state.py", line 32, in warn_or_err
    raise RuntimeError(msg)
RuntimeError: Found param backbones.ResNet18FPN.features.conv1.weight with type torch.FloatTensor, expected torch.cuda.FloatTensor.
When using amp.initialize, you need to provide a model with parameters
located on a CUDA device before passing it no matter what optimization level
you chose. Use model.to('cuda') to use the default device.
```

**Comment by james-nvidia** [comment]
It looks like you aren't copying your model to the GPU.

Are you running this inside the docker container? If so, which command did you use to launch the container? What GPU are you using?

**Comment by 372046933** [comment]
@james-nvidia I am using Tesla with `Driver Version: 410.79`. The problem was caused by low driver version. I can see the error reported when the container is started.
