### ISSUE TITLE
Jetson AGX NCCL Issue

### ISSUE THREAD

**Issue by tblake84** [NVIDIA/retinanet-examples#260]
I am using a Jetson AGX with JetPack 4.4.1 (R32.4.4) and the nvcr.io/nvidia/l4t-pytorch:r32.4.4-pth1.6-py3 docker image from NGC.
Installing setup.py from both 19.10 and 20.03 branches yield issues:

branch 20.03:
```
odtk infer /data/engine_5_class_finetuned_int8.plan --images /data/sample_inputs/
Traceback (most recent call last):
  File "/usr/local/bin/odtk", line 33, in <module>
    sys.exit(load_entry_point('odtk==0.2.4', 'console_scripts', 'odtk')())
  File "/usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/main.py", line 181, in main
    worker(0, args, 1, model, state)
  File "/usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/main.py", line 116, in worker
    torch.distributed.init_process_group(backend='nccl', init_method='env://')
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 432, in init_process_group
    timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/torch/distributed/distributed_c10d.py", line 508, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL "
RuntimeError: Distributed package doesn't have NCCL built in
```
branch 19.10:
```
Traceback (most recent call last):
  File "/usr/local/bin/odtk", line 33, in <module>
    sys.exit(load_entry_point('odtk==0.2.4', 'console_scripts', 'odtk')())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 473, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2447, in load
    return self.resolve()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 2453, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/model.py", line 8, in <module>
    from ._C import Engine
ImportError: /usr/local/lib/python3.6/dist-packages/retinanet-0.1-py3.6-linux-aarch64.egg/retinanet/_C.so: undefined symbol: _ZN2cv6imreadERKNS_6StringEi
```
After some troubleshooting I adjusted setup.py with the following:
```
        library_dirs=['/usr/local/lib', '/usr/local/lib64/'],
        libraries=['nvinfer', 'nvinfer_plugin', 'nvonnxparser', 'opencv_core', 'opencv_highgui', 'opencv_imgproc', 'opencv_imgcodecs'])
```
And now I am back to getting the NCCL error above.

**Comment by batrlatom** [comment]
It look like you need to have jetpack 4.3 installed .. viz. https://github.com/NVIDIA/retinanet-examples#jetpack-compatibility

**Comment by james-nvidia** [comment]
@tblake84 We have only tested with older versions, as per the comment above. Have you tried inferring using the DeepStream SDK? That would bypass your error messages.

**Comment by yashnv** [comment]
Closing due to inactivity.
