### ISSUE TITLE
Problem in attempt of training

### ISSUE THREAD

**Issue by samaujs** [NVIDIA/retinanet-examples#262]
Hi,
  I encountered the following error in the attempt of training after docker build on a DGX station : 

$ odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /data/open_images/train_faces --annotations /data/open_images/train_faces.json --val-images /data/open_images/validation --val-annotations /data/open_images/val_faces.json
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/workspace/retinanet/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/workspace/retinanet/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/workspace/retinanet/retinanet/model.py", line 30
    angles=None,
         ^
SyntaxError: invalid syntax
--
Any pointers will be useful.  Thanks.

**Comment by james-nvidia** [comment]
Please post the exact commands you used, including entering the docker container.

**Comment by samaujs** [comment]
Hi,
the command entering the docker container after building is : 
# **docker run --gpus all --rm --ipc=host -v /home/sam/personal/ml/examples/retinanet_for_redaction_with_deepstream/data:/data -it odtk:latest**

and the error occurred with the following command : 
root@beaa4e0eab93:/workspace# **odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /data/open_images/train_faces --annotations /data/open_images/train_faces.json --val-images /data/open_images/validation --val-annotations /data/open_images/val_faces.json**
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2462, in load
    return self.resolve()
  File "/opt/conda/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/workspace/retinanet/retinanet/main.py", line 10, in <module>
    from retinanet import infer, train, utils
  File "/workspace/retinanet/retinanet/infer.py", line 13, in <module>
    from .model import Model
  File "/workspace/retinanet/retinanet/model.py", line 30
    angles=None,
         ^
SyntaxError: invalid syntax
--

The Data preparation with the openimages dataset v5 is obtained by following the DATA_README.md at : 
https://github.com/NVIDIA-AI-IOT/retinanet_for_redaction_with_deepstream/blob/master/DATA_README.md

**Comment by yashnv** [comment]
Can you do a fresh clone inside docker, cd into the clone, and use `pip install --no-cache-dir -e .`?

**Comment by samaujs** [comment]
# docker run --gpus all --rm --ipc=host -v /home/sam/personal/ml/examples/retinanet_for_redaction_with_deepstream/data:/data -v /home/sam/personal/ml/examples:/src -it odtk:latest 

root@9ffccb5f5b30:/src# git clone https://github.com/nvidia/retinanet-examples
root@9ffccb5f5b30:/src# cd retinanet-examples
root@9ffccb5f5b30:/src/retinanet-examples# pip install --no-cache-dir -e .

root@9ffccb5f5b30:/src/retinanet-examples# odtk train retinanet_rn50fpn.pth --backbone ResNet50FPN --images /data/open_images/train_faces --annotations /data/open_images/train_faces.json --val-images /data/open_images/validation --val-annotations /data/open_images/val_faces.json

The error is resolved by re-cloning the example within the docker without the need to re-build.  Thank you.
