### ISSUE TITLE
Encountered errors with the inference on own dataset

### ISSUE THREAD

**Issue by samaujs** [NVIDIA/retinanet-examples#263]
Hi,
  There is no error with inference on open images v5 dataset : 

root@9ffccb5f5b30:/src/retinanet-examples# **odtk infer retinanet_rn50fpn.pth --images /data/open_images/val_faces --annotations /data/open_images/val_faces.json**

  But, I have encountered errors with the inference on own dataset : 

root@9ffccb5f5b30:/src/retinanet-examples# **odtk infer retinanet_rn50fpn.pth --images /data/open_images/owntest --output detections.json**
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
Process SpawnProcess-2:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/src/retinanet-examples/retinanet/main.py", line 190, in worker
    rotated_bbox=args.rotated_bbox)
  File "/src/retinanet-examples/retinanet/infer.py", line 71, in infer
    for i, (data, ids, ratios) in enumerate(data_iterator):
  File "/src/retinanet-examples/retinanet/data.py", line 217, in __iter__
    for output in self.dataloader:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 748, in __init__
    self._try_put_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 978, in _try_put_index
    index = self._next_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 341, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 68, in __iter__
    assert len(indices) == self.total_size
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 27, in _wrap
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/opt/conda/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 9634) is killed by signal: Terminated.
Process SpawnProcess-3:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/src/retinanet-examples/retinanet/main.py", line 190, in worker
    rotated_bbox=args.rotated_bbox)
  File "/src/retinanet-examples/retinanet/infer.py", line 71, in infer
    for i, (data, ids, ratios) in enumerate(data_iterator):
  File "/src/retinanet-examples/retinanet/data.py", line 217, in __iter__
    for output in self.dataloader:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 748, in __init__
    self._try_put_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 978, in _try_put_index
    index = self._next_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 341, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 68, in __iter__
    assert len(indices) == self.total_size
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 27, in _wrap
    sys.exit(1)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 261, in _bootstrap
    util._exit_function()
  File "/opt/conda/lib/python3.6/multiprocessing/util.py", line 319, in _exit_function
    p.join()
  File "/opt/conda/lib/python3.6/multiprocessing/process.py", line 124, in join
    res = self._popen.wait(timeout)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 50, in wait
    return self.poll(os.WNOHANG if timeout == 0.0 else 0)
  File "/opt/conda/lib/python3.6/multiprocessing/popen_fork.py", line 28, in poll
    pid, sts = os.waitpid(self.pid, flag)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 9687) is killed by signal: Terminated.
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 11, in <module>
    load_entry_point('odtk', 'console_scripts', 'odtk')()
  File "/src/retinanet-examples/retinanet/main.py", line 245, in main
    torch.multiprocessing.spawn(worker, args=(args, world, model, state), nprocs=world)
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 200, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 158, in start_processes
    while not context.join():
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 119, in join
    raise Exception(msg)
Exception:

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/torch/multiprocessing/spawn.py", line 20, in _wrap
    fn(i, *args)
  File "/src/retinanet-examples/retinanet/main.py", line 190, in worker
    rotated_bbox=args.rotated_bbox)
  File "/src/retinanet-examples/retinanet/infer.py", line 71, in infer
    for i, (data, ids, ratios) in enumerate(data_iterator):
  File "/src/retinanet-examples/retinanet/data.py", line 217, in __iter__
    for output in self.dataloader:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 281, in __iter__
    return _MultiProcessingDataLoaderIter(self)
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 748, in __init__
    self._try_put_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 978, in _try_put_index
    index = self._next_index()
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 341, in _next_index
    return next(self._sampler_iter)  # may raise StopIteration
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/sampler.py", line 200, in __iter__
    for idx in self.sampler:
  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/distributed.py", line 68, in __iter__
    assert len(indices) == self.total_size
AssertionError

It will be great to get some pointers.  Thank you.

**Comment by yashnv** [comment]
The format of annotations should exactly match the format of the COCO annotations, looks like the dataset being parsed is finding incorrect length in annotations.
