### ISSUE TITLE
AttributeError: 'SGD' object has no attribute 'optimizer'

### ISSUE THREAD

**Issue by monocongo** [NVIDIA/retinanet-examples#28]
I am fine-tuning the pre-trained RetinaNet model based on the ResNet50FPN backbone (retinanet_rn50fpn.pth) using a custom dataset of 3652 JPG images with corresponding annotations in PASCAL VOC format (XML). The images are located in ~/data/images and the annotations are located in ~/data/annotations.

Below is the training command, with the error output: 
```
retinanet train ~/model/retinanet_handgun.pth --fine-tune ~/model/retinanet_rn50fpn/retinanet_rn50fpn.pth --classes 1 --iters 10000 --val-iters 1000 --lr 0.0005 --resize 512 --jitter 480 640 --images ~/data/images  --annotations ~/data/annotations --val-annotations ~/data/annotations
Initializing model...
Fine-tuning weights from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 1, anchors: 9
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : 128.0
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 181, in main
    worker(0, args, 1, model, state)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 127, in worker
    metrics_url=args.post_metrics, logdir=args.logdir, verbose=(rank == 0))
  File "/opt/conda/lib/python3.6/site-packages/retinanet/train.py", line 47, in train
    scheduler = LambdaLR(optimizer.optimizer if mixed_precision else optimizer, schedule)
AttributeError: 'SGD' object has no attribute 'optimizer'
```

What differs in my case from what is documented is that I have used the latest NVIDIA PyTorch Docker image (19.05 rather than 19.04) and I am using PASCAL VOC annotations in XML format rather than JSON (perhaps this is where I'm shooting myself in the foot, I just noticed that only COCO JSON format is supported). Other than this I am following the steps outlined in the README and TRAINING pages.

Thanks in advance for any comments or suggestions that may get me past this issue.

**Comment by florischabert** [comment]
The issue come from a change in Apex available in the 19.05 image. We'll push the change soon but in the meantime you can either use 19.04 or use `LambdaLR(optimizer, schedule)`.

**Comment by piotr-anyvision** [comment]
Seing a similar error:
AttributeError: 'SGD' object has no attribute 'defaults'
`
Traceback (most recent call last):
  File "/home/snow_ripple/workspace/020_retinanet_nvidia/retinanet/eval_scripts.py", line 20, in <module>
    eval_combo()
  File "/home/snow_ripple/workspace/020_retinanet_nvidia/retinanet/eval_scripts.py", line 11, in eval_combo
    main(args=infer_args)
  File "/home/snow_ripple/workspace/020_retinanet_nvidia/retinanet/main.py", line 231, in main
    model, state = load_model(args, verbose=True)
  File "/home/snow_ripple/workspace/020_retinanet_nvidia/retinanet/main.py", line 128, in load_model
    model.save(state=state)
  File "/home/snow_ripple/workspace/020_retinanet_nvidia/retinanet/model.py", line 197, in save
    torch.save(checkpoint, save_path)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/serialization.py", line 224, in save
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/serialization.py", line 149, in _with_file_like
    return body(f)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/serialization.py", line 224, in <lambda>
    return _with_file_like(f, "wb", lambda f: _save(obj, f, pickle_module, pickle_protocol))
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/serialization.py", line 296, in _save
    pickler.dump(obj)
  File "/home/snow_ripple/anaconda3/envs/pytorch1/lib/python3.7/site-packages/torch/optim/optimizer.py", line 55, in __getstate__
    'defaults': self.defaults,
AttributeError: 'SGD' object has no attribute 'defaults'
`
@florischabert 
What version of apex should we use?

**Comment by yashnv** [comment]
@piotr-anyvision can you try out the [19.09 branch](https://github.com/NVIDIA/retinanet-examples/tree/19.09)?
