### ISSUE TITLE
Size mismatch if fine-tuning

### ISSUE THREAD

**Issue by razimgit** [NVIDIA/retinanet-examples#293]
- Command I ran:
   ```
    odtk train ft_retinanet_rn18fpn.pth \
    --fine-tune retinanet_rn18fpn/retinanet_rn18fpn.pth \
    --backbone ResNet18FPN \
    --images /dataset/ready_dataset/traffic_lights_coco/dataset/train/ \
    --val-images /dataset/ready_dataset/traffic_lights_coco/dataset/test/ \
    --annotations /dataset/ready_dataset/traffic_lights_coco/dataset/annotations/train.json \
    --val-annotations /dataset/ready_dataset/traffic_lights_coco/dataset/annotations/test.json \
    --classes 5 --iters 32100 --val-iters 3210 --milestones 16050 25680 \
    --lr 0.001 --warmup 500 --batch 16 \
    --resize 320 --max-size 320 --jitter 320 320 \
    --logdir logs
   ```
- Container and `odtk`: v0.2.6
- Checkpoint: https://github.com/NVIDIA/retinanet-examples/releases/download/19.04/retinanet_rn18fpn.zip

Gives me a `size mismatch for box_head.8.bias`:
<details>
<summary>Error message</summary>

```
Initializing model...
Fine-tuning weights from retinanet_rn18fpn.pth...
Traceback (most recent call last):
  File "/opt/conda/bin/odtk", line 33, in <module>
    sys.exit(load_entry_point('odtk', 'console_scripts', 'odtk')())
  File "/workspace/odtk/odtk/main.py", line 244, in main
    model, state = load_model(args, verbose=True)
  File "/workspace/odtk/odtk/main.py", line 133, in load_model
    model.initialize(args.fine_tune)
  File "/workspace/odtk/odtk/model.py", line 94, in initialize
    self.load_state_dict(state_dict)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1054, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Model:
        size mismatch for box_head.8.weight: copying a param with shape torch.Size([36, 256, 3, 3]) from checkpoint, the shape in current model is torch.Size([48, 256, 3, 3]).
        size mismatch for box_head.8.bias: copying a param with shape torch.Size([36]) from checkpoint, the shape in current model is torch.Size([48]).
```
</details>

If I omit the fine-tuning and try training from scratch, there's no mismatch.
Is this caused by the outdated checkpoint? If so, any chance you could provide updated models?

**Comment by razimgit** [comment]
I had changed the number of anchor ratios, so the resulting number of anchors, which affects the `box_head`, conflicted with the checkpoint. I added `box_head.8.bias`, `box_head.8.weight` to the ignored weights in `initialize`, so it's fine now.
