### ISSUE TITLE
Error during validation iteration while fine-tuning the model

### ISSUE THREAD

**Issue by apoorvgarg10** [NVIDIA/retinanet-examples#296]
**Training command**:  odtk train sdd_rn18.pth --fine-tune /data/models/retinanet_rn18fpn/retinanet_rn18fpn/retinanet_rn18fpn.pth --classes 6 --iters 4000 --lr 0.0005 --resize 512 --jitter 480 640 --images /data/train/Images/ --annotations /data/train/train_fname_ext_inc.json --val-images /data/val/Images/ --val-annotations /data/val/val_fname_ext_inc.json --backbone ResNet18FPN --val-iters 200 --batch 1

**GPU used**: GTX1080 

**Branch**: master (Commit msg: [master] {origin/master} {origin/HEAD} v0.2.6). pytorch container is the same as mentioned in dockerfile.

**Steps used to build and run odtk**: 
1.) sudo docker build -t odtk:latest retinanet-examples/
2.)  sudo docker run --gpus all --rm  --ipc=host -v /home/test/Documents/COCOjson:/data -it odtk:latest

I am getting an error whenever inference in run (File infer.py). This can be after training the given iterations or after every val-iters. The training iterations are running fine and I can see a diverging focal loss. On putting debug prints, I could see that the collate function is running 4 times (depending on the batch size) but the data iterator class __iter__ does not return a list.
How can I debug this error?

> Traceback (most recent call last):
>   File "/opt/conda/bin/odtk", line 33, in <module>
>     sys.exit(load_entry_point('odtk', 'console_scripts', 'odtk')())
>   File "/workspace/odtk/odtk/main.py", line 249, in main
>     worker(0, args, 1, model, state)
>   File "/workspace/odtk/odtk/main.py", line 186, in worker
>     regularization_l2=args.regularization_l2, rotated_bbox=args.rotated_bbox, absolute_angle=args.absolute_angle)
>   File "/workspace/odtk/odtk/train.py", line 192, in train
>     is_validation=True, verbose=True, rotated_bbox=rotated_bbox)
>   File "/workspace/odtk/odtk/infer.py", line 79, in infer
>     for i, (data, ids, ratios) in enumerate(data_iterator):
>   File "/workspace/odtk/odtk/data.py", line 217, in __iter__
>     for output in self.dataloader:
>   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 438, in __next__
>     data = self._next_data()
>   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1088, in _next_data
>     return self._process_data(data)
>   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1114, in _process_data
>     data.reraise()
>   File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
>     raise self.exc_type(msg)
> ValueError: Caught ValueError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/workspace/odtk/odtk/data.py", line 181, in collate_fn
>     return data, torch.IntTensor(indices), ratios
> ValueError: too many dimensions 'str'

**Note:** The segmentation field in train/validation set is empty. Dies this lead to the error? I am doubthing this because the code returns error while running: `for i, (data, ids, ratios) in enumerate(data_iterator) ` in file infer.py and the segmentation fields are not queried till that point.

**Comment by apoorvgarg10** [comment]
This issue comes up because the image_id field in my dataset was stores as a string instead of int. The obvious bug fix is to typecast in the dataset itself.
But I did typecast to integer in the collate_fn and this got the train with validation to work. This will also require a string to integer typecast in the docker container pycocotools while evaluating the model.
