### ISSUE TITLE
CUDA error: no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by monocongo** [NVIDIA/retinanet-examples#33]
When I run a fine-tuning I get the following error:
```
$ retinanet train ~/retinanet_pytorch/handgun_pytorch_retinanet.pth \
--fine-tune ~/retinanet_pytorch/retinanet_rn50fpn/retinanet_rn50fpn.pth \
--classes 1 --iters 10000 --val-iters 1000 --lr 0.0005 --resize 512 \
--jitter 480 640 --images $BASE_DIR/images \
--annotations $BASE_DIR/annotations/coco/handgun_coco_training.json \
--val-annotations $BASE_DIR/annotations/coco/handgun_coco_validation.json 

Initializing model...
Fine-tuning weights from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 1, anchors: 9
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : 128.0
Traceback (most recent call last):
  File "/opt/conda/bin/retinanet", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 182, in main
    worker(0, args, 1, model, state)
  File "/opt/conda/lib/python3.6/site-packages/retinanet/main.py", line 128, in worker
    metrics_url=args.post_metrics, logdir=args.logdir, verbose=(rank == 0))
  File "/opt/conda/lib/python3.6/site-packages/retinanet/train.py", line 34, in train
    verbosity = is_master)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/frontend.py", line 339, in initialize
    return _initialize(models, optimizers, _amp_state.opt_properties, num_losses, cast_model_outputs)
  File "/opt/conda/lib/python3.6/site-packages/apex/amp/_initialize.py", line 159, in _initialize
    convert_network(model, properties.cast_model_type)
  File "/opt/conda/lib/python3.6/site-packages/apex/fp16_utils/fp16util.py", line 67, in convert_network
    convert_module(module, dtype)
  File "/opt/conda/lib/python3.6/site-packages/apex/fp16_utils/fp16util.py", line 51, in convert_module
    param.data = param.data.to(dtype=dtype)
RuntimeError: CUDA error: no kernel image is available for execution on the device
```

I am running this on an EC2 instance (p2.xlarge, Ubuntu 18.04) with Tesla K80 GPU:
```
$ nvidia-smi
Sat Jun  8 02:34:34 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 430.14       Driver Version: 430.14       CUDA Version: 10.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla K80           Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   45C    P0    76W / 149W |      0MiB / 11441MiB |     95%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
```

Can anyone advise as to what might be causing this error and/or how I might work around it? Please advise if I can provide any further environment details that may help diagnose this issue. Thanks in advance for any assistance, comments, or suggestions.

**Comment by florischabert** [comment]
We do not support pre-Pascal GPUs in this project.

**Comment by monocongo** [comment]
Is there a list of GPU types that are supported, in order to help me choose a more appropriate EC2 instance type for this training?

**Comment by florischabert** [comment]
this project has the same requirements as the NGC container it is based on, see "GPU Requirements" here: https://docs.nvidia.com/deeplearning/frameworks/pytorch-release-notes/rel_19-05.html#rel_19-05
