### ISSUE TITLE
RuntimeError: Loss is diverging! Try lowering the learning rate.

### ISSUE THREAD

**Issue by jinfagang** [NVIDIA/retinanet-examples#81]
Train on 1 card, already set lr to: 0.00125, gots:

```
Loading model from retinanet_rn50fpn.pth...
     model: RetinaNet
  backbone: ResNet50FPN
   classes: 80, anchors: 9
####### lr: 0.00125
####### warmup: 125
Selected optimization level O2:  FP16 training with FP32 batchnorm and FP32 master weights.

Defaults for this optimization level are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O2
cast_model_type        : torch.float16
patch_torch_functions  : False
keep_batchnorm_fp32    : True
master_weights         : True
loss_scale             : 128.0
Warning:  multi_tensor_applier fused unscale kernel is unavailable, possibly because apex was installed without --cuda_ext --cpp_ext. Using Python fallback.  Original ImportError was: ModuleNotFoundError("No module named 'amp_C'",)
Preparing dataset...
    loader: pytorch
    resize: [640, 1024], max: 1333
    device: 1 gpu
    batch: 2, precision: mixed
Training model for 90000 iterations...
[ 1122/90000] focal loss: 1.245, box loss: 0.452, 0.492s/2-batch (fw: 0.186s, bw: 0.303s), 4.1 im/s, lr: 0.01
[ 1248/90000] focal loss: 1.186, box loss: 0.451, 0.478s/2-batch (fw: 0.176s, bw: 0.301s), 4.2 im/s, lr: 0.01
[ 1374/90000] focal loss: 1.098, box loss: 0.457, 0.479s/2-batch (fw: 0.177s, bw: 0.301s), 4.2 im/s, lr: 0.01
[ 1496/90000] focal loss: 1.065, box loss: 0.451, 0.494s/2-batch (fw: 0.184s, bw: 0.310s), 4.0 im/s, lr: 0.01
Traceback (most recent call last):
  File "/usr/local/bin/retinanet", line 8, in <module>
    sys.exit(main())
  File "/p/retinanet-examples/retinanet/main.py", line 183, in main
    worker(0, args, 1, model, state)
  File "/p/retinanet-examples/retinanet/main.py", line 129, in worker
    metrics_url=args.post_metrics, logdir=args.logdir, verbose=(rank == 0))
  File "/p/retinanet-examples/retinanet/train.py", line 106, in train
    'Try lowering the learning rate.'))
RuntimeError: Loss is diverging!
Try lowering the learning rate.

```

**Comment by yashnv** [comment]
Please try different lr/warmup configurations. The original values don't necessarily need to scale with the number of GPUs.
